### PR TITLE
Fixed state not respecting word boundaries.

### PR DESCRIPTION
**Pull request by Jcw87**
Fixes issue #5

I've never written unit tests before, so let me know if I need to change something.

### CODE REVIEW

**Comment by jamesrcounts** [comment]
Hi, thanks for the PR.  Unfortunately, your change breaks an existing test case in `ParseExampleAddresses`.  "9999 ATLANTIC AVE BROOKLYN, N.Y. 99999" no longer matches after the change to the regex.  If you can figure out a way to make the change you want without breaking the existing examples we can go forward with this PR.

I'm setting up AppVeyor so that we can autorun tests on PRs in the future.

**Comment by Jcw87** [comment]
I looked at the [source for the original module](http://cpansearch.perl.org/src/TIMB/Geo-StreetAddress-US-1.04/US.pm), and it would appear that it doesn't handle the "N.Y." case either. I don't know for sure, as I don't want to install pearl on this machine.

I don't think trying to fix this case by changing or adding on to the already mammoth regex is a good idea. I think the better approach is to (perhaps optionally) pre-process the input to remove common problematic periods. Maybe something like this:

`var reg = new Regex(@"(\w)\.(\w)\.\s*")`
`input = reg.Replace(input, "\1\2 ")`

I think this would fix the "N.Y." case, as well as improve your normalized PO box case, which currently goes from "P.O.Box 9999" to "POBOX 9999", and would change to "PO BOX 9999".

What are your thoughts on this?

**Comment by jamesrcounts** [comment]
So, I'm wary of rocking the boat.  This version of the package has been pretty stable for a long time and gets a decent number of downloads.  I know that the place I worked when I forked it from CodePlex is using it to parse many thousands of addresses per day.

I think the N.Y. example was one of these that was a very important case that justified actually creating a "fake" example to include in the open source library.  So I don't want to accept anything that breaks existing tests.  The idea of scrubbing out the dots is probably too broad.  People do all kinds of crazy things when writing down addresses.

On the other hand, the address regex itself is lazy and that's a feature we used to build parsers for edge cases.  It doesn't construct the monolithic regex until the first time you try to `get` `AddressRegex`.  My suggestion is that you submit a PR which adds a setter to the `StatePattern` string so that you can override its value to meet your use case.  It seems like the current pattern is already meeting the majority of use cases.

Then you just need to write a test that shows the override value shows up in AddressRegex, just like the `AddressRegexIsLazy` test.

**Comment by Jcw87** [comment]
I decided to test the address parser with [a zip code database](http://federalgovernmentzipcodes.us/), and found that, with your current implementation, about 11,000 valid entries failed to parse correctly. My previous change brought it down to around 1,000, but the remaining entries revealed a larger problem. So, I made a different change, and brought it down to about 100 (all in Puerto Rico, and all with numbers in the city name). I've changed the unit test I created to reflect the new change.

This change doesn't seem to break any tests, other than the ones that just check the generated regex.

**Comment by jamesrcounts** [comment]
That's really great! 

If you would, go ahead and approve the test results that lock down the generated regex (Assuming the changes that you see there accurately reflect the changes you expected.)

Then we'll let AppVeyor run again and get a clean build.

**Pull request merged**
